// OpenGL 1.0 core bindings

// OpenGL types

pub const GLvoid = void;
pub const GLboolean = u8;
pub const GLbyte = i8;
pub const GLubyte = u8;
pub const GLshort = i16;
pub const GLushort = u16;
pub const GLint = i32;
pub const GLuint = u32;
pub const GLsizei = i32;
pub const GLenum = u32;
pub const GLbitfield = u32;
pub const GLfloat = f32;
pub const GLclampf = f32;
pub const GLdouble = f64;
pub const GLclampd = f64;

// OpenGL Commands

pub extern fn glAccum(op: GLenum, value: GLfloat) void;
pub extern fn glAlphaFunc(func: GLenum, ref: GLclampf) void;
pub extern fn glBegin(mode: GLenum) void;
pub extern fn glBitmap(width: GLsizei, height: GLsizei, xorig: GLfloat, yorig: GLfloat, xmove: GLfloat, ymove: GLfloat, bitmap: ?[*]const GLubyte) void;
pub extern fn glBlendFunc(sfactor: GLenum, dfactor: GLenum) void;
pub extern fn glCallList(list: GLuint) void;
pub extern fn glCallLists(n: GLsizei, type_: GLenum, lists: ?*const anyopaque) void;
pub extern fn glClear(mask: GLbitfield) void;
pub extern fn glClearAccum(red: GLfloat, green: GLfloat, blue: GLfloat, alpha: GLfloat) void;
pub extern fn glClearColor(red: GLclampf, green: GLclampf, blue: GLclampf, alpha: GLclampf) void;
pub extern fn glClearDepth(depth: GLclampd) void;
pub extern fn glClearIndex(c: GLfloat) void;
pub extern fn glClearStencil(s: GLint) void;
pub extern fn glClipPlane(plane: GLenum, equation: ?[*]const GLdouble) void;
pub extern fn glColor3b(red: GLbyte, green: GLbyte, blue: GLbyte) void;
pub extern fn glColor3d(red: GLdouble, green: GLdouble, blue: GLdouble) void;
pub extern fn glColor3f(red: GLfloat, green: GLfloat, blue: GLfloat) void;
pub extern fn glColor3i(red: GLint, green: GLint, blue: GLint) void;
pub extern fn glColor3s(red: GLshort, green: GLshort, blue: GLshort) void;
pub extern fn glColor3ub(red: GLubyte, green: GLubyte, blue: GLubyte) void;
pub extern fn glColor3ui(red: GLuint, green: GLuint, blue: GLuint) void;
pub extern fn glColor3us(red: GLushort, green: GLushort, blue: GLushort) void;
pub extern fn glColor4b(red: GLbyte, green: GLbyte, blue: GLbyte, alpha: GLbyte) void;
pub extern fn glColor4d(red: GLdouble, green: GLdouble, blue: GLdouble, alpha: GLdouble) void;
pub extern fn glColor4f(red: GLfloat, green: GLfloat, blue: GLfloat, alpha: GLfloat) void;
pub extern fn glColor4i(red: GLint, green: GLint, blue: GLint, alpha: GLint) void;
pub extern fn glColor4s(red: GLshort, green: GLshort, blue: GLshort, alpha: GLshort) void;
pub extern fn glColor4ub(red: GLubyte, green: GLubyte, blue: GLubyte, alpha: GLubyte) void;
pub extern fn glColor4ui(red: GLuint, green: GLuint, blue: GLuint, alpha: GLuint) void;
pub extern fn glColor4us(red: GLushort, green: GLushort, blue: GLushort, alpha: GLushort) void;
pub extern fn glColor3bv(v: ?[*]const GLbyte) void;
pub extern fn glColor3dv(v: ?[*]const GLdouble) void;
pub extern fn glColor3fv(v: ?[*]const GLfloat) void;
pub extern fn glColor3iv(v: ?[*]const GLint) void;
pub extern fn glColor3sv(v: ?[*]const GLshort) void;
pub extern fn glColor3ubv(v: ?[*]const GLubyte) void;
pub extern fn glColor3uiv(v: ?[*]const GLuint) void;
pub extern fn glColor3usv(v: ?[*]const GLushort) void;
pub extern fn glColor4bv(v: ?[*]const GLbyte) void;
pub extern fn glColor4dv(v: ?[*]const GLdouble) void;
pub extern fn glColor4fv(v: ?[*]const GLfloat) void;
pub extern fn glColor4iv(v: ?[*]const GLint) void;
pub extern fn glColor4sv(v: ?[*]const GLshort) void;
pub extern fn glColor4ubv(v: ?[*]const GLubyte) void;
pub extern fn glColor4uiv(v: ?[*]const GLuint) void;
pub extern fn glColor4usv(v: ?[*]const GLushort) void;
pub extern fn glColorMask(red: GLboolean, green: GLboolean, blue: GLboolean, alpha: GLboolean) void;
pub extern fn glColorMaterial(face: GLenum, mode: GLenum) void;
pub extern fn glCopyPixels(x: GLint, y: GLint, width: GLsizei, height: GLsizei, type_: GLenum) void;
pub extern fn glCullFace(mode: GLenum) void;
pub extern fn glDeleteLists(list: GLuint, range: GLsizei) void;
pub extern fn glDepthFunc(func: GLenum) void;
pub extern fn glDepthMask(flag: GLboolean) void;
pub extern fn glDepthRange(near: GLclampd, far: GLclampd) void;
pub extern fn glDisable(cap: GLenum) void;
pub extern fn glDrawBuffer(mode: GLenum) void;
pub extern fn glDrawPixels(width: GLsizei, height: GLsizei, format: GLenum, type_: GLenum, pixels: ?*const anyopaque) void;
pub extern fn glEdgeFlag(flag: GLboolean) void;
pub extern fn glEdgeFlagv(flag: ?[*]const GLboolean) void;
pub extern fn glEnable(cap: GLenum) void;
pub extern fn glEnd() void;
pub extern fn glEndList() void;
pub extern fn glEvalCoord1d(u: GLdouble) void;
pub extern fn glEvalCoord1f(u: GLfloat) void;
pub extern fn glEvalCoord1dv(u: ?[*]const GLdouble) void;
pub extern fn glEvalCoord1fv(u: ?[*]const GLfloat) void;
pub extern fn glEvalCoord2d(u: GLdouble, v: GLdouble) void;
pub extern fn glEvalCoord2f(u: GLfloat, v: GLfloat) void;
pub extern fn glEvalCoord2dv(u: ?[*]const GLdouble) void;
pub extern fn glEvalCoord2fv(u: ?[*]const GLfloat) void;
pub extern fn glEvalMesh1(mode: GLenum, i1: GLint, i2: GLint) void;
pub extern fn glEvalMesh2(mode: GLenum, i1: GLint, i2: GLint, j1: GLint, j2: GLint) void;
pub extern fn glEvalPoint1(i: GLint) void;
pub extern fn glEvalPoint2(i: GLint, j: GLint) void;

pub extern fn glFeedbackBuffer(size: GLsizei, type_: GLenum, buffer: ?[*]GLfloat) void;
pub extern fn glFinish() void;
pub extern fn glFlush() void;
pub extern fn glFogf(pname: GLenum, param: GLfloat) void;
pub extern fn glFogi(pname: GLenum, param: GLint) void;
pub extern fn glFogfv(pname: GLenum, params: ?[*]const GLfloat) void;
pub extern fn glFogiv(pname: GLenum, params: ?[*]const GLint) void;
pub extern fn glFrontFace(mode: GLenum) void;
pub extern fn glFrustum(left: GLdouble, right: GLdouble, bottom: GLdouble, top: GLdouble, near: GLdouble, far: GLdouble) void;
pub extern fn glGenLists(range: GLsizei) GLuint;
pub extern fn glGetBooleanv(pname: GLenum, params: ?[*]GLboolean) void;
pub extern fn glGetClipPlane(plane: GLenum, equation: ?[*]GLdouble) void;
pub extern fn glGetDoublev(pname: GLenum, params: ?[*]GLdouble) void;
pub extern fn glGetError() GLenum;
pub extern fn glGetFloatv(pname: GLenum, params: ?[*]GLfloat) void;
pub extern fn glGetIntegerv(pname: GLenum, params: ?[*]GLint) void;
pub extern fn glGetLightfv(light: GLenum, pname: GLenum, params: ?[*]GLfloat) void;
pub extern fn glGetLightiv(light: GLenum, pname: GLenum, params: ?[*]GLint) void;
pub extern fn glGetMapdv(target: GLenum, query: GLenum, v: ?[*]GLdouble) void;
pub extern fn glGetMapfv(target: GLenum, query: GLenum, v: ?[*]GLfloat) void;
pub extern fn glGetMapiv(target: GLenum, query: GLenum, v: ?[*]GLint) void;
pub extern fn glGetMaterialfv(face: GLenum, pname: GLenum, params: ?[*]GLfloat) void;
pub extern fn glGetMaterialiv(face: GLenum, pname: GLenum, params: ?[*]GLint) void;
pub extern fn glGetPixelMapfv(map: GLenum, values: ?[*]GLfloat) void;
pub extern fn glGetPixelMapuiv(map: GLenum, values: ?[*]GLuint) void;
pub extern fn glGetPixelMapusv(map: GLenum, values: ?[*]GLushort) void;
pub extern fn glGetPolygonStipple(mask: ?[*]GLubyte) void;
pub extern fn glGetString(name: GLenum) ?[*:0]const GLubyte;
pub extern fn glGetTexEnvfv(target: GLenum, pname: GLenum, params: ?[*]GLfloat) void;
pub extern fn glGetTexEnviv(target: GLenum, pname: GLenum, params: ?[*]GLint) void;
pub extern fn glGetTexGendv(coord: GLenum, pname: GLenum, params: ?[*]GLdouble) void;
pub extern fn glGetTexGenfv(coord: GLenum, pname: GLenum, params: ?[*]GLfloat) void;
pub extern fn glGetTexGeniv(coord: GLenum, pname: GLenum, params: ?[*]GLint) void;
pub extern fn glGetTexImage(target: GLenum, level: GLint, format: GLenum, type_: GLenum, pixels: ?*anyopaque) void;
pub extern fn glGetTexLevelParameterfv(target: GLenum, level: GLint, pname: GLenum, params: ?[*]GLfloat) void;
pub extern fn glGetTexLevelParameteriv(target: GLenum, level: GLint, pname: GLenum, params: ?[*]GLint) void;
pub extern fn glGetTexParameterfv(target: GLenum, pname: GLenum, params: ?[*]GLfloat) void;
pub extern fn glGetTexParameteriv(target: GLenum, pname: GLenum, params: ?[*]GLint) void;
pub extern fn glHintf(target: GLenum, mode: GLenum) void;
pub extern fn glHinti(target: GLenum, mode: GLenum) void;
pub extern fn glIndexd(c: GLdouble) void;
pub extern fn glIndexf(c: GLfloat) void;
pub extern fn glIndexi(c: GLint) void;
pub extern fn glIndexs(c: GLshort) void;
pub extern fn glIndexub(c: GLubyte) void;
pub extern fn glIndexdv(c: ?[*]const GLdouble) void;
pub extern fn glIndexfv(c: ?[*]const GLfloat) void;
pub extern fn glIndexiv(c: ?[*]const GLint) void;
pub extern fn glIndexsv(c: ?[*]const GLshort) void;
pub extern fn glIndexubv(c: ?[*]const GLubyte) void;
pub extern fn glIndexMask(mask: GLuint) void;
pub extern fn glInitNames() void;
pub extern fn glIsEnabled(cap: GLenum) GLboolean;
pub extern fn glIsList(list: GLuint) GLboolean;
pub extern fn glLightf(light: GLenum, pname: GLenum, param: GLfloat) void;
pub extern fn glLighti(light: GLenum, pname: GLenum, param: GLint) void;
pub extern fn glLightfv(light: GLenum, pname: GLenum, params: ?[*]const GLfloat) void;
pub extern fn glLightiv(light: GLenum, pname: GLenum, params: ?[*]const GLint) void;
pub extern fn glLightModelf(pname: GLenum, param: GLfloat) void;
pub extern fn glLightModeli(pname: GLenum, param: GLint) void;
pub extern fn glLightModelfv(pname: GLenum, params: ?[*]const GLfloat) void;
pub extern fn glLightModeliv(pname: GLenum, params: ?[*]const GLint) void;
pub extern fn glLineStipple(factor: GLint, pattern: GLushort) void;
pub extern fn glLineWidth(width: GLfloat) void;
pub extern fn glListBase(base: GLuint) void;
pub extern fn glLoadIdentity() void;
pub extern fn glLoadMatrixd(m: ?[*]const GLdouble) void;
pub extern fn glLoadMatrixf(m: ?[*]const GLfloat) void;
pub extern fn glLoadName(name: GLuint) void;
pub extern fn glLogicOp(opcode: GLenum) void;
pub extern fn glMap1d(target: GLenum, u1: GLdouble, u2: GLdouble, stride: GLint, order: GLint, points: ?[*]const GLdouble) void;
pub extern fn glMap1f(target: GLenum, u1: GLfloat, u2: GLfloat, stride: GLint, order: GLint, points: ?[*]const GLfloat) void;
pub extern fn glMap2d(target: GLenum, u1: GLdouble, u2: GLdouble, ustride: GLint, uorder: GLint, v1: GLdouble, v2: GLdouble, vstride: GLint, vorder: GLint, points: ?[*]const GLdouble) void;
pub extern fn glMap2f(target: GLenum, u1: GLfloat, u2: GLfloat, ustride: GLint, uorder: GLint, v1: GLfloat, v2: GLfloat, vstride: GLint, vorder: GLint, points: ?[*]const GLfloat) void;
pub extern fn glMapGrid1d(un: GLint, u1: GLdouble, u2: GLdouble) void;
pub extern fn glMapGrid1f(un: GLint, u1: GLfloat, u2: GLfloat) void;
pub extern fn glMapGrid2d(un: GLint, u1: GLdouble, u2: GLdouble, vn: GLint, v1: GLdouble, v2: GLdouble) void;
pub extern fn glMapGrid2f(un: GLint, u1: GLfloat, u2: GLfloat, vn: GLint, v1: GLfloat, v2: GLfloat) void;
pub extern fn glMaterialf(face: GLenum, pname: GLenum, param: GLfloat) void;
pub extern fn glMateriali(face: GLenum, pname: GLenum, param: GLint) void;
pub extern fn glMaterialfv(face: GLenum, pname: GLenum, params: ?[*]const GLfloat) void;
pub extern fn glMaterialiv(face: GLenum, pname: GLenum, params: ?[*]const GLint) void;
pub extern fn glMatrixMode(mode: GLenum) void;
pub extern fn glMultMatrixd(m: ?[*]const GLdouble) void;
pub extern fn glMultMatrixf(m: ?[*]const GLfloat) void;
pub extern fn glNewList(list: GLuint, mode: GLenum) void;
pub extern fn glNormal3b(nx: GLbyte, ny: GLbyte, nz: GLbyte) void;
pub extern fn glNormal3d(nx: GLdouble, ny: GLdouble, nz: GLdouble) void;
pub extern fn glNormal3f(nx: GLfloat, ny: GLfloat, nz: GLfloat) void;
pub extern fn glNormal3i(nx: GLint, ny: GLint, nz: GLint) void;
pub extern fn glNormal3s(nx: GLshort, ny: GLshort, nz: GLshort) void;
pub extern fn glNormal3bv(v: ?[*]const GLbyte) void;
pub extern fn glNormal3dv(v: ?[*]const GLdouble) void;
pub extern fn glNormal3fv(v: ?[*]const GLfloat) void;
pub extern fn glNormal3iv(v: ?[*]const GLint) void;
pub extern fn glNormal3sv(v: ?[*]const GLshort) void;
pub extern fn glOrtho(left: GLdouble, right: GLdouble, bottom: GLdouble, top: GLdouble, near: GLdouble, far: GLdouble) void;
pub extern fn glPassThrough(token: GLfloat) void;
pub extern fn glPixelMapfv(map: GLenum, mapsize: GLint, values: ?[*]const GLfloat) void;
pub extern fn glPixelMapuiv(map: GLenum, mapsize: GLint, values: ?[*]const GLuint) void;
pub extern fn glPixelMapusv(map: GLenum, mapsize: GLint, values: ?[*]const GLushort) void;
pub extern fn glPixelStoref(pname: GLenum, param: GLfloat) void;
pub extern fn glPixelStorei(pname: GLenum, param: GLint) void;
pub extern fn glPixelTransferf(pname: GLenum, param: GLfloat) void;
pub extern fn glPixelTransferi(pname: GLenum, param: GLint) void;
pub extern fn glPixelZoom(xfactor: GLfloat, yfactor: GLfloat) void;
pub extern fn glPointSize(size: GLfloat) void;
pub extern fn glPolygonMode(face: GLenum, mode: GLenum) void;
pub extern fn glPolygonStipple(mask: ?[*]const GLubyte) void;
pub extern fn glPopAttrib() void;
pub extern fn glPopMatrix() void;
pub extern fn glPopName() void;
pub extern fn glPushAttrib(mask: GLbitfield) void;
pub extern fn glPushMatrix() void;
pub extern fn glPushName(name: GLuint) void;
pub extern fn glRasterPos2d(x: GLdouble, y: GLdouble) void;
pub extern fn glRasterPos2f(x: GLfloat, y: GLfloat) void;
pub extern fn glRasterPos2i(x: GLint, y: GLint) void;
pub extern fn glRasterPos2s(x: GLshort, y: GLshort) void;
pub extern fn glRasterPos2dv(v: ?[*]const GLdouble) void;
pub extern fn glRasterPos2fv(v: ?[*]const GLfloat) void;
pub extern fn glRasterPos2iv(v: ?[*]const GLint) void;
pub extern fn glRasterPos2sv(v: ?[*]const GLshort) void;
pub extern fn glRasterPos3d(x: GLdouble, y: GLdouble, z: GLdouble) void;
pub extern fn glRasterPos3f(x: GLfloat, y: GLfloat, z: GLfloat) void;
pub extern fn glRasterPos3i(x: GLint, y: GLint, z: GLint) void;
pub extern fn glRasterPos3s(x: GLshort, y: GLshort, z: GLshort) void;
pub extern fn glRasterPos3dv(v: ?[*]const GLdouble) void;
pub extern fn glRasterPos3fv(v: ?[*]const GLfloat) void;
pub extern fn glRasterPos3iv(v: ?[*]const GLint) void;
pub extern fn glRasterPos3sv(v: ?[*]const GLshort) void;
pub extern fn glRasterPos4d(x: GLdouble, y: GLdouble, z: GLdouble, w: GLdouble) void;
pub extern fn glRasterPos4f(x: GLfloat, y: GLfloat, z: GLfloat, w: GLfloat) void;
pub extern fn glRasterPos4i(x: GLint, y: GLint, z: GLint, w: GLint) void;
pub extern fn glRasterPos4s(x: GLshort, y: GLshort, z: GLshort, w: GLshort) void;
pub extern fn glRasterPos4dv(v: ?[*]const GLdouble) void;
pub extern fn glRasterPos4fv(v: ?[*]const GLfloat) void;
pub extern fn glRasterPos4iv(v: ?[*]const GLint) void;
pub extern fn glRasterPos4sv(v: ?[*]const GLshort) void;
pub extern fn glReadBuffer(mode: GLenum) void;
pub extern fn glReadPixels(x: GLint, y: GLint, width: GLsizei, height: GLsizei, format: GLenum, type_: GLenum, pixels: ?*anyopaque) void;
pub extern fn glRectd(x1: GLdouble, y1: GLdouble, x2: GLdouble, y2: GLdouble) void;
pub extern fn glRectf(x1: GLfloat, y1: GLfloat, x2: GLfloat, y2: GLfloat) void;
pub extern fn glRecti(x1: GLint, y1: GLint, x2: GLint, y2: GLint) void;
pub extern fn glRects(x1: GLshort, y1: GLshort, x2: GLshort, y2: GLshort) void;
pub extern fn glRectdv(v1: ?[*]const GLdouble, v2: ?[*]const GLdouble) void;
pub extern fn glRectfv(v1: ?[*]const GLfloat, v2: ?[*]const GLfloat) void;
pub extern fn glRectiv(v1: ?[*]const GLint, v2: ?[*]const GLint) void;
pub extern fn glRectsv(v1: ?[*]const GLshort, v2: ?[*]const GLshort) void;
pub extern fn glRenderMode(mode: GLenum) GLint;

pub extern fn glRotated(angle: GLdouble, x: GLdouble, y: GLdouble, z: GLdouble) void;
pub extern fn glRotatef(angle: GLfloat, x: GLfloat, y: GLfloat, z: GLfloat) void;
pub extern fn glScaled(x: GLdouble, y: GLdouble, z: GLdouble) void;
pub extern fn glScalef(x: GLfloat, y: GLfloat, z: GLfloat) void;
pub extern fn glScissor(x: GLint, y: GLint, width: GLsizei, height: GLsizei) void;
pub extern fn glSelectBuffer(size: GLsizei, buffer: ?[*]GLuint) void;
pub extern fn glShadeModel(mode: GLenum) void;
pub extern fn glStencilFunc(func: GLenum, ref: GLint, mask: GLuint) void;
pub extern fn glStencilMask(mask: GLuint) void;
pub extern fn glStencilOp(fail: GLenum, zfail: GLenum, zpass: GLenum) void;
pub extern fn glTexCoord1d(s: GLdouble) void;
pub extern fn glTexCoord1f(s: GLfloat) void;
pub extern fn glTexCoord1i(s: GLint) void;
pub extern fn glTexCoord1s(s: GLshort) void;
pub extern fn glTexCoord1dv(v: ?[*]const GLdouble) void;
pub extern fn glTexCoord1fv(v: ?[*]const GLfloat) void;
pub extern fn glTexCoord1iv(v: ?[*]const GLint) void;
pub extern fn glTexCoord1sv(v: ?[*]const GLshort) void;
pub extern fn glTexCoord2d(s: GLdouble, t: GLdouble) void;
pub extern fn glTexCoord2f(s: GLfloat, t: GLfloat) void;
pub extern fn glTexCoord2i(s: GLint, t: GLint) void;
pub extern fn glTexCoord2s(s: GLshort, t: GLshort) void;
pub extern fn glTexCoord2dv(v: ?[*]const GLdouble) void;
pub extern fn glTexCoord2fv(v: ?[*]const GLfloat) void;
pub extern fn glTexCoord2iv(v: ?[*]const GLint) void;
pub extern fn glTexCoord2sv(v: ?[*]const GLshort) void;
pub extern fn glTexCoord3d(s: GLdouble, t: GLdouble, r: GLdouble) void;
pub extern fn glTexCoord3f(s: GLfloat, t: GLfloat, r: GLfloat) void;
pub extern fn glTexCoord3i(s: GLint, t: GLint, r: GLint) void;
pub extern fn glTexCoord3s(s: GLshort, t: GLshort, r: GLshort) void;
pub extern fn glTexCoord3dv(v: ?[*]const GLdouble) void;
pub extern fn glTexCoord3fv(v: ?[*]const GLfloat) void;
pub extern fn glTexCoord3iv(v: ?[*]const GLint) void;
pub extern fn glTexCoord3sv(v: ?[*]const GLshort) void;
pub extern fn glTexCoord4d(s: GLdouble, t: GLdouble, r: GLdouble, q: GLdouble) void;
pub extern fn glTexCoord4f(s: GLfloat, t: GLfloat, r: GLfloat, q: GLfloat) void;
pub extern fn glTexCoord4i(s: GLint, t: GLint, r: GLint, q: GLint) void;
pub extern fn glTexCoord4s(s: GLshort, t: GLshort, r: GLshort, q: GLshort) void;
pub extern fn glTexCoord4dv(v: ?[*]const GLdouble) void;
pub extern fn glTexCoord4fv(v: ?[*]const GLfloat) void;
pub extern fn glTexCoord4iv(v: ?[*]const GLint) void;
pub extern fn glTexCoord4sv(v: ?[*]const GLshort) void;
pub extern fn glTexEnvf(target: GLenum, pname: GLenum, param: GLfloat) void;
pub extern fn glTexEnvi(target: GLenum, pname: GLenum, param: GLint) void;
pub extern fn glTexEnvfv(target: GLenum, pname: GLenum, params: ?[*]const GLfloat) void;
pub extern fn glTexEnviv(target: GLenum, pname: GLenum, params: ?[*]const GLint) void;
pub extern fn glTexGend(coord: GLenum, pname: GLenum, param: GLdouble) void;
pub extern fn glTexGenf(coord: GLenum, pname: GLenum, param: GLfloat) void;
pub extern fn glTexGeni(coord: GLenum, pname: GLenum, param: GLint) void;
pub extern fn glTexGendv(coord: GLenum, pname: GLenum, params: ?[*]const GLdouble) void;
pub extern fn glTexGenfv(coord: GLenum, pname: GLenum, params: ?[*]const GLfloat) void;
pub extern fn glTexGeniv(coord: GLenum, pname: GLenum, params: ?[*]const GLint) void;
pub extern fn glTexImage1D(target: GLenum, level: GLint, internalformat: GLint, width: GLsizei, border: GLint, format: GLenum, type_: GLenum, pixels: ?*const anyopaque) void;
pub extern fn glTexImage2D(target: GLenum, level: GLint, internalformat: GLint, width: GLsizei, height: GLsizei, border: GLint, format: GLenum, type_: GLenum, pixels: ?*const anyopaque) void;
pub extern fn glTexParameterf(target: GLenum, pname: GLenum, param: GLfloat) void;
pub extern fn glTexParameteri(target: GLenum, pname: GLenum, param: GLint) void;
pub extern fn glTexParameterfv(target: GLenum, pname: GLenum, params: ?[*]const GLfloat) void;
pub extern fn glTexParameteriv(target: GLenum, pname: GLenum, params: ?[*]const GLint) void;
pub extern fn glTranslated(x: GLdouble, y: GLdouble, z: GLdouble) void;
pub extern fn glTranslatef(x: GLfloat, y: GLfloat, z: GLfloat) void;
pub extern fn glVertex2d(x: GLdouble, y: GLdouble) void;
pub extern fn glVertex2f(x: GLfloat, y: GLfloat) void;
pub extern fn glVertex2i(x: GLint, y: GLint) void;
pub extern fn glVertex2s(x: GLshort, y: GLshort) void;
pub extern fn glVertex2dv(v: ?[*]const GLdouble) void;
pub extern fn glVertex2fv(v: ?[*]const GLfloat) void;
pub extern fn glVertex2iv(v: ?[*]const GLint) void;
pub extern fn glVertex2sv(v: ?[*]const GLshort) void;
pub extern fn glVertex3d(x: GLdouble, y: GLdouble, z: GLdouble) void;
pub extern fn glVertex3f(x: GLfloat, y: GLfloat, z: GLfloat) void;
pub extern fn glVertex3i(x: GLint, y: GLint, z: GLint) void;
pub extern fn glVertex3s(x: GLshort, y: GLshort, z: GLshort) void;
pub extern fn glVertex3dv(v: ?[*]const GLdouble) void;
pub extern fn glVertex3fv(v: ?[*]const GLfloat) void;
pub extern fn glVertex3iv(v: ?[*]const GLint) void;
pub extern fn glVertex3sv(v: ?[*]const GLshort) void;
pub extern fn glVertex4d(x: GLdouble, y: GLdouble, z: GLdouble, w: GLdouble) void;
pub extern fn glVertex4f(x: GLfloat, y: GLfloat, z: GLfloat, w: GLfloat) void;
pub extern fn glVertex4i(x: GLint, y: GLint, z: GLint, w: GLint) void;
pub extern fn glVertex4s(x: GLshort, y: GLshort, z: GLshort, w: GLshort) void;
pub extern fn glVertex4dv(v: ?[*]const GLdouble) void;
pub extern fn glVertex4fv(v: ?[*]const GLfloat) void;
pub extern fn glVertex4iv(v: ?[*]const GLint) void;
pub extern fn glVertex4sv(v: ?[*]const GLshort) void;
pub extern fn glViewport(x: GLint, y: GLint, width: GLsizei, height: GLsizei) void;

//

pub const GL_FALSE: GLboolean = 0;
pub const GL_TRUE: GLboolean = 1;
pub const GL_BYTE: GLenum = 0x1400;
pub const GL_UNSIGNED_BYTE: GLenum = 0x1401;
pub const GL_SHORT: GLenum = 0x1402;
pub const GL_UNSIGNED_SHORT: GLenum = 0x1403;
pub const GL_INT: GLenum = 0x1404;
pub const GL_UNSIGNED_INT: GLenum = 0x1405;
pub const GL_FLOAT: GLenum = 0x1406;
pub const GL_DOUBLE: GLenum = 0x140A;
pub const GL_2_BYTES: GLenum = 0x1407;
pub const GL_3_BYTES: GLenum = 0x1408;
pub const GL_4_BYTES: GLenum = 0x1409;
pub const GL_POINTS: GLenum = 0x0000;
pub const GL_LINES: GLenum = 0x0001;
pub const GL_LINE_LOOP: GLenum = 0x0002;
pub const GL_LINE_STRIP: GLenum = 0x0003;
pub const GL_TRIANGLES: GLenum = 0x0004;
pub const GL_TRIANGLE_STRIP: GLenum = 0x0005;
pub const GL_TRIANGLE_FAN: GLenum = 0x0006;
pub const GL_QUADS: GLenum = 0x0007;
pub const GL_QUAD_STRIP: GLenum = 0x0008;
pub const GL_POLYGON: GLenum = 0x0009;
pub const GL_ACCUM: GLenum = 0x0100;
pub const GL_LOAD: GLenum = 0x0101;
pub const GL_RETURN: GLenum = 0x0102;
pub const GL_MULT: GLenum = 0x0103;
pub const GL_ADD: GLenum = 0x0104;
pub const GL_NEVER: GLenum = 0x0200;
pub const GL_LESS: GLenum = 0x0201;
pub const GL_EQUAL: GLenum = 0x0202;
pub const GL_LEQUAL: GLenum = 0x0203;
pub const GL_GREATER: GLenum = 0x0204;
pub const GL_NOTEQUAL: GLenum = 0x0205;
pub const GL_GEQUAL: GLenum = 0x0206;
pub const GL_ALWAYS: GLenum = 0x0207;
pub const GL_CURRENT_BIT: GLbitfield = 0x00000001;
pub const GL_POINT_BIT: GLbitfield = 0x00000002;
pub const GL_LINE_BIT: GLbitfield = 0x00000004;
pub const GL_POLYGON_BIT: GLbitfield = 0x00000008;
pub const GL_POLYGON_STIPPLE_BIT: GLbitfield = 0x00000010;
pub const GL_PIXEL_MODE_BIT: GLbitfield = 0x00000020;
pub const GL_LIGHTING_BIT: GLbitfield = 0x00000040;
pub const GL_FOG_BIT: GLbitfield = 0x00000080;
pub const GL_DEPTH_BUFFER_BIT: GLbitfield = 0x00000100;
pub const GL_ACCUM_BUFFER_BIT: GLbitfield = 0x00000200;
pub const GL_STENCIL_BUFFER_BIT: GLbitfield = 0x00000400;
pub const GL_VIEWPORT_BIT: GLbitfield = 0x00000800;
pub const GL_TRANSFORM_BIT: GLbitfield = 0x00001000;
pub const GL_ENABLE_BIT: GLbitfield = 0x00002000;
pub const GL_COLOR_BUFFER_BIT: GLbitfield = 0x00004000;
pub const GL_HINT_BIT: GLbitfield = 0x00008000;
pub const GL_EVAL_BIT: GLbitfield = 0x00010000;
pub const GL_LIST_BIT: GLbitfield = 0x00020000;
pub const GL_TEXTURE_BIT: GLbitfield = 0x00040000;
pub const GL_SCISSOR_BIT: GLbitfield = 0x00080000;
pub const GL_ALL_ATTRIB_BITS: GLbitfield = 0x000FFFFF;
pub const GL_QUAD_BIT: GLbitfield = 0x00000008;

pub const GL_POLYGON_MODE: GLenum = 0x0B40;
pub const GL_POLYGON_SMOOTH: GLenum = 0x0B41;
pub const GL_POLYGON_STIPPLE: GLenum = 0x0B42;
pub const GL_EDGE_FLAG: GLenum = 0x0B43;
pub const GL_CULL_FACE: GLenum = 0x0B44;
pub const GL_CULL_FACE_MODE: GLenum = 0x0B45;
pub const GL_FRONT_FACE: GLenum = 0x0B46;
pub const GL_LIGHTING: GLenum = 0x0B50;
pub const GL_LIGHT_MODEL_LOCAL_VIEWER: GLenum = 0x0B53;
pub const GL_LIGHT_MODEL_TWO_SIDE: GLenum = 0x0B54;
pub const GL_LIGHT_MODEL_AMBIENT: GLenum = 0x0B53;
pub const GL_SHADE_MODEL: GLenum = 0x0B54;
pub const GL_COLOR_MATERIAL_FACE: GLenum = 0x0B55;
pub const GL_COLOR_MATERIAL_PARAMETER: GLenum = 0x0B56;
pub const GL_COLOR_MATERIAL: GLenum = 0x0B57;
pub const GL_FOG: GLenum = 0x0B60;
pub const GL_FOG_INDEX: GLenum = 0x0B61;
pub const GL_FOG_DENSITY: GLenum = 0x0B62;
pub const GL_FOG_START: GLenum = 0x0B63;
pub const GL_FOG_END: GLenum = 0x0B64;
pub const GL_FOG_MODE: GLenum = 0x0B65;
pub const GL_FOG_COLOR: GLenum = 0x0B66;
pub const GL_DEPTH_TEST: GLenum = 0x0B71;
pub const GL_DEPTH_WRITEMASK: GLenum = 0x0B72;
pub const GL_DEPTH_CLEAR_VALUE: GLenum = 0x0B73;
pub const GL_DEPTH_FUNC: GLenum = 0x0B74;
pub const GL_ACCUM_CLEAR_VALUE: GLenum = 0x0B80;
pub const GL_STENCIL_TEST: GLenum = 0x0B90;
pub const GL_STENCIL_CLEAR_VALUE: GLenum = 0x0B91;
pub const GL_STENCIL_FUNC: GLenum = 0x0B92;
pub const GL_STENCIL_VALUE_MASK: GLenum = 0x0B93;
pub const GL_STENCIL_FAIL: GLenum = 0x0B94;
pub const GL_STENCIL_PASS_DEPTH_FAIL: GLenum = 0x0B95;
pub const GL_STENCIL_PASS_DEPTH_PASS: GLenum = 0x0B96;
pub const GL_STENCIL_REF: GLenum = 0x0B97;
pub const GL_STENCIL_WRITEMASK: GLenum = 0x0B98;
pub const GL_MATRIX_MODE: GLenum = 0x0BA0;
pub const GL_NORMALIZE: GLenum = 0x0BA1;
pub const GL_VIEWPORT: GLenum = 0x0BA2;
pub const GL_MODELVIEW_STACK_DEPTH: GLenum = 0x0BA3;
pub const GL_PROJECTION_STACK_DEPTH: GLenum = 0x0BA4;
pub const GL_TEXTURE_STACK_DEPTH: GLenum = 0x0BA5;
pub const GL_MODELVIEW_MATRIX: GLenum = 0x0BA6;
pub const GL_PROJECTION_MATRIX: GLenum = 0x0BA7;
pub const GL_TEXTURE_MATRIX: GLenum = 0x0BA8;

pub const GL_ATTRIB_STACK_DEPTH: GLenum = 0x0BB0;

pub const GL_ALPHA_TEST: GLenum = 0x0BC0;
pub const GL_ALPHA_TEST_FUNC: GLenum = 0x0BC1;
pub const GL_ALPHA_TEST_REF: GLenum = 0x0BC2;
pub const GL_DITHER: GLenum = 0x0BD0;
pub const GL_BLEND_DST: GLenum = 0x0BE0;
pub const GL_BLEND_SRC: GLenum = 0x0BE1;
pub const GL_BLEND: GLenum = 0x0BE2;
pub const GL_LOGIC_OP_MODE: GLenum = 0x0BF0;
pub const GL_INDEX_LOGIC_OP: GLenum = 0x0BF1;
pub const GL_COLOR_LOGIC_OP: GLenum = 0x0BF2;
pub const GL_AUX_BUFFERS: GLenum = 0x0C00;
pub const GL_DRAW_BUFFER: GLenum = 0x0C01;
pub const GL_READ_BUFFER: GLenum = 0x0C02;
pub const GL_SCISSOR_BOX: GLenum = 0x0C10;
pub const GL_SCISSOR_TEST: GLenum = 0x0C11;
pub const GL_INDEX_CLEAR_VALUE: GLenum = 0x0C20;
pub const GL_INDEX_WRITEMASK: GLenum = 0x0C21;
pub const GL_COLOR_CLEAR_VALUE: GLenum = 0x0C22;
pub const GL_COLOR_WRITEMASK: GLenum = 0x0C23;
pub const GL_INDEX_MODE: GLenum = 0x0C30;
pub const GL_RGBA_MODE: GLenum = 0x0C31;
pub const GL_DOUBLEBUFFER: GLenum = 0x0C32;
pub const GL_STEREO: GLenum = 0x0C33;
pub const GL_RENDER_MODE: GLenum = 0x0C40;
pub const GL_PERSPECTIVE_CORRECTION_HINT: GLenum = 0x0C50;
pub const GL_POINT_SMOOTH_HINT: GLenum = 0x0C51;
pub const GL_LINE_SMOOTH_HINT: GLenum = 0x0C52;
pub const GL_POLYGON_SMOOTH_HINT: GLenum = 0x0C53;
pub const GL_FOG_HINT: GLenum = 0x0C54;
pub const GL_TEXTURE_GEN_S: GLenum = 0x0C60;
pub const GL_TEXTURE_GEN_T: GLenum = 0x0C61;
pub const GL_TEXTURE_GEN_R: GLenum = 0x0C62;
pub const GL_TEXTURE_GEN_Q: GLenum = 0x0C63;
pub const GL_PIXEL_MAP_I_TO_I: GLenum = 0x0C70;
pub const GL_PIXEL_MAP_S_TO_S: GLenum = 0x0C71;
pub const GL_PIXEL_MAP_I_TO_R: GLenum = 0x0C72;
pub const GL_PIXEL_MAP_I_TO_G: GLenum = 0x0C73;
pub const GL_PIXEL_MAP_I_TO_B: GLenum = 0x0C74;
pub const GL_PIXEL_MAP_I_TO_A: GLenum = 0x0C75;
pub const GL_PIXEL_MAP_R_TO_R: GLenum = 0x0C76;
pub const GL_PIXEL_MAP_G_TO_G: GLenum = 0x0C77;
pub const GL_PIXEL_MAP_B_TO_B: GLenum = 0x0C78;
pub const GL_PIXEL_MAP_A_TO_A: GLenum = 0x0C79;
pub const GL_PIXEL_MAP_I_TO_I_SIZE: GLenum = 0x0CB0;
pub const GL_PIXEL_MAP_S_TO_S_SIZE: GLenum = 0x0CB1;
pub const GL_PIXEL_MAP_I_TO_R_SIZE: GLenum = 0x0CB2;
pub const GL_PIXEL_MAP_I_TO_G_SIZE: GLenum = 0x0CB3;
pub const GL_PIXEL_MAP_I_TO_B_SIZE: GLenum = 0x0CB4;
pub const GL_PIXEL_MAP_I_TO_A_SIZE: GLenum = 0x0CB5;
pub const GL_PIXEL_MAP_R_TO_R_SIZE: GLenum = 0x0CB6;
pub const GL_PIXEL_MAP_G_TO_G_SIZE: GLenum = 0x0CB7;
pub const GL_PIXEL_MAP_B_TO_B_SIZE: GLenum = 0x0CB8;
pub const GL_PIXEL_MAP_A_TO_A_SIZE: GLenum = 0x0CB9;
pub const GL_UNPACK_SWAP_BYTES: GLenum = 0x0CF0;
pub const GL_UNPACK_LSB_FIRST: GLenum = 0x0CF1;
pub const GL_UNPACK_ROW_LENGTH: GLenum = 0x0CF2;
pub const GL_UNPACK_SKIP_ROWS: GLenum = 0x0CF3;
pub const GL_UNPACK_SKIP_PIXELS: GLenum = 0x0CF4;
pub const GL_UNPACK_ALIGNMENT: GLenum = 0x0CF5;
pub const GL_PACK_SWAP_BYTES: GLenum = 0x0D00;
pub const GL_PACK_LSB_FIRST: GLenum = 0x0D01;
pub const GL_PACK_ROW_LENGTH: GLenum = 0x0D02;
pub const GL_PACK_SKIP_ROWS: GLenum = 0x0D03;
pub const GL_PACK_SKIP_PIXELS: GLenum = 0x0D04;
pub const GL_PACK_ALIGNMENT: GLenum = 0x0D05;
pub const GL_PACK_IMAGE_HEIGHT: GLenum = 0x806C;
pub const GL_PACK_SKIP_IMAGES: GLenum = 0x806B;
pub const GL_UNPACK_IMAGE_HEIGHT: GLenum = 0x806E;
pub const GL_UNPACK_SKIP_IMAGES: GLenum = 0x806D;
pub const GL_TEXTURE_1D: GLenum = 0x0DE0;
pub const GL_TEXTURE_2D: GLenum = 0x0DE1;
pub const GL_TEXTURE_WIDTH: GLenum = 0x1000;
pub const GL_TEXTURE_HEIGHT: GLenum = 0x1001;
pub const GL_TEXTURE_INTERNAL_FORMAT: GLenum = 0x1003;
pub const GL_TEXTURE_COMPONENTS: GLenum = 0x1003;
pub const GL_TEXTURE_BORDER_COLOR: GLenum = 0x1004;
pub const GL_TEXTURE_BORDER: GLenum = 0x1005;
pub const GL_TEXTURE_RED_SIZE: GLenum = 0x805C;
pub const GL_TEXTURE_GREEN_SIZE: GLenum = 0x805D;
pub const GL_TEXTURE_BLUE_SIZE: GLenum = 0x805E;
pub const GL_TEXTURE_ALPHA_SIZE: GLenum = 0x805F;
pub const GL_TEXTURE_LUMINANCE_SIZE: GLenum = 0x8060;
pub const GL_TEXTURE_INTENSITY_SIZE: GLenum = 0x8061;
pub const GL_REPLACE: GLenum = 0x1E01;
pub const GL_TEXTURE_PRIORITY: GLenum = 0x8066;
pub const GL_TEXTURE_RESIDENT: GLenum = 0x8067;
pub const GL_VERTEX_ARRAY: GLenum = 0x8074;
pub const GL_NORMAL_ARRAY: GLenum = 0x8075;
pub const GL_COLOR_ARRAY: GLenum = 0x8076;
pub const GL_INDEX_ARRAY: GLenum = 0x8077;
pub const GL_TEXTURE_COORD_ARRAY: GLenum = 0x8078;
pub const GL_EDGE_FLAG_ARRAY: GLenum = 0x8079;
pub const GL_VERTEX_ARRAY_SIZE: GLenum = 0x807A;
pub const GL_VERTEX_ARRAY_TYPE: GLenum = 0x807B;
pub const GL_VERTEX_ARRAY_STRIDE: GLenum = 0x807C;
pub const GL_NORMAL_ARRAY_TYPE: GLenum = 0x807E;
pub const GL_NORMAL_ARRAY_STRIDE: GLenum = 0x807F;
pub const GL_COLOR_ARRAY_SIZE: GLenum = 0x8081;
pub const GL_COLOR_ARRAY_TYPE: GLenum = 0x8082;
pub const GL_COLOR_ARRAY_STRIDE: GLenum = 0x8083;
pub const GL_INDEX_ARRAY_TYPE: GLenum = 0x8085;
pub const GL_INDEX_ARRAY_STRIDE: GLenum = 0x8086;
pub const GL_TEXTURE_COORD_ARRAY_SIZE: GLenum = 0x8088;
pub const GL_TEXTURE_COORD_ARRAY_TYPE: GLenum = 0x8089;
pub const GL_TEXTURE_COORD_ARRAY_STRIDE: GLenum = 0x808A;
pub const GL_EDGE_FLAG_ARRAY_STRIDE: GLenum = 0x808C;

pub const GL_VERTEX_ARRAY_POINTER: GLenum = 0x808E;
pub const GL_NORMAL_ARRAY_POINTER: GLenum = 0x808F;
pub const GL_COLOR_ARRAY_POINTER: GLenum = 0x8090;
pub const GL_INDEX_ARRAY_POINTER: GLenum = 0x8091;
pub const GL_TEXTURE_COORD_ARRAY_POINTER: GLenum = 0x8092;
pub const GL_EDGE_FLAG_ARRAY_POINTER: GLenum = 0x8093;
pub const GL_V2F: GLenum = 0x2A20;
pub const GL_V3F: GLenum = 0x2A21;
pub const GL_C4UB_V2F: GLenum = 0x2A22;
pub const GL_C4UB_V3F: GLenum = 0x2A23;
pub const GL_C3F_V3F: GLenum = 0x2A24;
pub const GL_N3F_V3F: GLenum = 0x2A25;
pub const GL_C4F_N3F_V3F: GLenum = 0x2A26;
pub const GL_T2F_V3F: GLenum = 0x2A27;
pub const GL_T4F_V4F: GLenum = 0x2A28;
pub const GL_T2F_C4UB_V3F: GLenum = 0x2A29;
pub const GL_T2F_C3F_V3F: GLenum = 0x2A2A;
pub const GL_T2F_N3F_V3F: GLenum = 0x2A2B;
pub const GL_T2F_C4F_N3F_V3F: GLenum = 0x2A2C;
pub const GL_T4F_C4F_N3F_V4F: GLenum = 0x2A2D;
pub const GL_MODELVIEW: GLenum = 0x1700;
pub const GL_PROJECTION: GLenum = 0x1701;
pub const GL_TEXTURE: GLenum = 0x1702;
pub const GL_POINT_SMOOTH: GLenum = 0x0B10;
pub const GL_POINT_SIZE: GLenum = 0x0B11;
pub const GL_POINT_SIZE_GRANULARITY: GLenum = 0x0B13;
pub const GL_POINT_SIZE_RANGE: GLenum = 0x0B12;
pub const GL_LINE_SMOOTH: GLenum = 0x0B20;
pub const GL_LINE_STIPPLE: GLenum = 0x0B24;
pub const GL_LINE_STIPPLE_PATTERN: GLenum = 0x0B25;
pub const GL_LINE_STIPPLE_REPEAT: GLenum = 0x0B26;
pub const GL_LINE_WIDTH: GLenum = 0x0B21;
pub const GL_LINE_WIDTH_GRANULARITY: GLenum = 0x0B23;
pub const GL_LINE_WIDTH_RANGE: GLenum = 0x0B22;
pub const GL_LIGHT_MODEL_COLOR_CONTROL: GLenum = 0x81F8;
pub const GL_LIGHT0: GLenum = 0x4000;
pub const GL_LIGHT1: GLenum = 0x4001;
pub const GL_LIGHT2: GLenum = 0x4002;
pub const GL_LIGHT3: GLenum = 0x4003;
pub const GL_LIGHT4: GLenum = 0x4004;
pub const GL_LIGHT5: GLenum = 0x4005;
pub const GL_LIGHT6: GLenum = 0x4006;
pub const GL_LIGHT7: GLenum = 0x4007;
pub const GL_SPOT_EXPONENT: GLenum = 0x1205;
pub const GL_SPOT_CUTOFF: GLenum = 0x1206;
pub const GL_CONSTANT_ATTENUATION: GLenum = 0x1207;
pub const GL_LINEAR_ATTENUATION: GLenum = 0x1208;
pub const GL_QUADRATIC_ATTENUATION: GLenum = 0x1209;
pub const GL_AMBIENT: GLenum = 0x1200;
pub const GL_DIFFUSE: GLenum = 0x1201;
pub const GL_SPECULAR: GLenum = 0x1202;
pub const GL_SHININESS: GLenum = 0x1601;
pub const GL_EMISSION: GLenum = 0x1600;
pub const GL_FRONT: GLenum = 0x0404;
pub const GL_BACK: GLenum = 0x0405;
pub const GL_FRONT_AND_BACK: GLenum = 0x0408;
pub const GL_FLAT: GLenum = 0x1D00;
pub const GL_SMOOTH: GLenum = 0x1D01;
pub const GL_HINT: GLenum = 0x0C00;
pub const GL_HINT_TARGET: GLenum = 0x0C01;
pub const GL_FASTEST: GLenum = 0x1101;
pub const GL_NICEST: GLenum = 0x1102;
pub const GL_DONT_CARE: GLenum = 0x1100;
pub const GL_AMBIENT_AND_DIFFUSE: GLenum = 0x1602;
pub const GL_LINEAR: GLenum = 0x2601;
pub const GL_EXP: GLenum = 0x0800;
pub const GL_EXP2: GLenum = 0x0801;
pub const GL_LOGIC_OP: GLenum = 0x0BF1;
pub const GL_TEXTURE_MIN_FILTER: GLenum = 0x2801;
pub const GL_TEXTURE_MAG_FILTER: GLenum = 0x2800;
pub const GL_TEXTURE_WRAP_S: GLenum = 0x2802;
pub const GL_TEXTURE_WRAP_T: GLenum = 0x2803;
pub const GL_NEAREST: GLenum = 0x2600;
pub const GL_NEAREST_MIPMAP_NEAREST: GLenum = 0x2700;
pub const GL_LINEAR_MIPMAP_NEAREST: GLenum = 0x2701;
pub const GL_NEAREST_MIPMAP_LINEAR: GLenum = 0x2702;
pub const GL_LINEAR_MIPMAP_LINEAR: GLenum = 0x2703;
pub const GL_REPEAT: GLenum = 0x2901;
pub const GL_CLAMP: GLenum = 0x2900;

pub const GL_EYE_LINEAR: GLenum = 0x2400;
pub const GL_OBJECT_LINEAR: GLenum = 0x2401;
pub const GL_SPHERE_MAP: GLenum = 0x2402;
pub const GL_TEXTURE_GEN_MODE: GLenum = 0x2500;
pub const GL_OBJECT_PLANE: GLenum = 0x2501;
pub const GL_EYE_PLANE: GLenum = 0x2502;
